version: '3'
services:
  service:
    container_name: service
    build: ./app
    expose:
      - "8000"
    volumes:
      - static_volume:/opt/app/static
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/opt/app/static
    depends_on:
      - service
    ports:
      - "80:80"
    restart: always

  theatre-db:
    container_name: theatre_db
    image: postgres:latest
    depends_on:
      - nginx
    environment:
      - DB_NAME=${SQL_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=${SQL_OPTIONS}
    ports:
      - "5432:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  static_volume:
