version: '3.8'

services:
  theatre-db:
    container_name: theatre_db
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=${SQL_OPTIONS}
    ports:
      - "5432:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  service:
    container_name: service
    build: ./app
    expose:
      - "8000"
    volumes:
      - static_volume:/opt/app/static
    env_file:
      - ./.env
    depends_on:
      - theatre-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:1.25.3
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/opt/app/static
    depends_on:
      - service
    ports:
      - "80:80"
    restart: always

volumes:
  static_volume:
